sonar.projectKey=UPT-FAING-EPIS_proyecto-si783-2026-i-u3-migrador_bd
sonar.organization=upt-faing-epis
sonar.sources=proyecto-si783-2026-i-u1-migrador-de-bd-codigo-web/app,proyecto-si783-2026-i-u1-migrador-de-bd-codigo-web/carga,proyecto-si783-2026-i-u1-migrador-de-bd-codigo-web/extraccion,proyecto-si783-2026-i-u1-migrador-de-bd-codigo-web/transformacion
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=**/tests/**,**/migrations/**,**/.venv/**
